
package Calculadora;

/**
 *
 * @author JuanBarrios
 */
public class CalculadoraP extends javax.swing.JFrame {

    public float Num1;
    public float Num2;
    public String Operator;

    public String CalculoCero(float resul) {
        String retorno = "";
        retorno = Float.toString(resul);
        if (resul % 1 == 0) {
            retorno = retorno.substring(0, retorno.length() - 2);
        }
        return retorno;
    }

    public CalculadoraP() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Ingreso = new javax.swing.JLabel();
        ButtonMul = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        ButtonRes = new javax.swing.JButton();
        ButtonDiv = new javax.swing.JButton();
        ButtonNueve = new javax.swing.JButton();
        ButtonSiete = new javax.swing.JButton();
        ButtonOcho = new javax.swing.JButton();
        ButtonSeis = new javax.swing.JButton();
        ButtonCuatro = new javax.swing.JButton();
        ButtonSum = new javax.swing.JButton();
        ButtonCinco = new javax.swing.JButton();
        ButtonTres = new javax.swing.JButton();
        ButtonUno = new javax.swing.JButton();
        ButtonDos = new javax.swing.JButton();
        ButtonPunt = new javax.swing.JButton();
        ButtonCero = new javax.swing.JButton();
        ButtonResul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Label_Ingreso.setBackground(new java.awt.Color(153, 153, 153));
        Label_Ingreso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Ingreso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label_Ingreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        Label_Ingreso.setOpaque(true);

        ButtonMul.setBackground(new java.awt.Color(153, 153, 153));
        ButtonMul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonMul.setText("*");
        ButtonMul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMulActionPerformed(evt);
            }
        });

        ButtonC.setBackground(new java.awt.Color(153, 153, 153));
        ButtonC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonC.setText("C");
        ButtonC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });

        ButtonRes.setBackground(new java.awt.Color(153, 153, 153));
        ButtonRes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonRes.setText("-");
        ButtonRes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResActionPerformed(evt);
            }
        });

        ButtonDiv.setBackground(new java.awt.Color(153, 153, 153));
        ButtonDiv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonDiv.setText("/");
        ButtonDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivActionPerformed(evt);
            }
        });

        ButtonNueve.setBackground(new java.awt.Color(153, 153, 153));
        ButtonNueve.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonNueve.setText("9");
        ButtonNueve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNueveActionPerformed(evt);
            }
        });

        ButtonSiete.setBackground(new java.awt.Color(153, 153, 153));
        ButtonSiete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonSiete.setText("7");
        ButtonSiete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSieteActionPerformed(evt);
            }
        });

        ButtonOcho.setBackground(new java.awt.Color(153, 153, 153));
        ButtonOcho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonOcho.setText("8");
        ButtonOcho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOchoActionPerformed(evt);
            }
        });

        ButtonSeis.setBackground(new java.awt.Color(153, 153, 153));
        ButtonSeis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonSeis.setText("6");
        ButtonSeis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSeisActionPerformed(evt);
            }
        });

        ButtonCuatro.setBackground(new java.awt.Color(153, 153, 153));
        ButtonCuatro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonCuatro.setText("4");
        ButtonCuatro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCuatroActionPerformed(evt);
            }
        });

        ButtonSum.setBackground(new java.awt.Color(153, 153, 153));
        ButtonSum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonSum.setText("+");
        ButtonSum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSumActionPerformed(evt);
            }
        });

        ButtonCinco.setBackground(new java.awt.Color(153, 153, 153));
        ButtonCinco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonCinco.setText("5");
        ButtonCinco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCincoActionPerformed(evt);
            }
        });

        ButtonTres.setBackground(new java.awt.Color(153, 153, 153));
        ButtonTres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonTres.setText("3");
        ButtonTres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTresActionPerformed(evt);
            }
        });

        ButtonUno.setBackground(new java.awt.Color(153, 153, 153));
        ButtonUno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonUno.setText("1");
        ButtonUno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUnoActionPerformed(evt);
            }
        });

        ButtonDos.setBackground(new java.awt.Color(153, 153, 153));
        ButtonDos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonDos.setText("2");
        ButtonDos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDosActionPerformed(evt);
            }
        });

        ButtonPunt.setBackground(new java.awt.Color(153, 153, 153));
        ButtonPunt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonPunt.setText(".");
        ButtonPunt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonPunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPuntActionPerformed(evt);
            }
        });

        ButtonCero.setBackground(new java.awt.Color(153, 153, 153));
        ButtonCero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonCero.setText("0");
        ButtonCero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCeroActionPerformed(evt);
            }
        });

        ButtonResul.setBackground(new java.awt.Color(153, 153, 153));
        ButtonResul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonResul.setText("=");
        ButtonResul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ButtonResul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonRes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonResul, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonRes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ButtonResul, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCeroActionPerformed
        this.Label_Ingreso.setText(this.Label_Ingreso.getText() + "0");
    }//GEN-LAST:event_ButtonCeroActionPerformed

    private void ButtonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUnoActionPerformed
        this.Label_Ingreso.setText(this.Label_Ingreso.getText() + "1");
    }//GEN-LAST:event_ButtonUnoActionPerformed

    private void ButtonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDosActionPerformed
        this.Label_Ingreso.setText(this.Label_Ingreso.getText() + "2");
    }//GEN-LAST:event_ButtonDosActionPerformed

    private void ButtonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTresActionPerformed
        this.Label_Ingreso.setText(this.Label_Ingreso.getText() + "3");
    }//GEN-LAST:event_ButtonTresActionPerformed

    private void ButtonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCuatroActionPerformed
        this.Label_Ingreso.setText(this.Label_Ingreso.getText() + "4");
    }//GEN-LAST:event_ButtonCuatroActionPerformed

    private void ButtonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCincoActionPerformed
        this.Label_Ingreso.setText(this.Label_Ingreso.getText() + "5");
    }//GEN-LAST:event_ButtonCincoActionPerformed

    private void ButtonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSeisActionPerformed
        this.Label_Ingreso.setText(this.Label_Ingreso.getText() + "6");
    }//GEN-LAST:event_ButtonSeisActionPerformed

    private void ButtonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSieteActionPerformed
        this.Label_Ingreso.setText(this.Label_Ingreso.getText() + "7");
    }//GEN-LAST:event_ButtonSieteActionPerformed

    private void ButtonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOchoActionPerformed
        this.Label_Ingreso.setText(this.Label_Ingreso.getText() + "8");
    }//GEN-LAST:event_ButtonOchoActionPerformed

    private void ButtonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNueveActionPerformed
        this.Label_Ingreso.setText(this.Label_Ingreso.getText() + "9");
    }//GEN-LAST:event_ButtonNueveActionPerformed

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        this.Label_Ingreso.setText("");
    }//GEN-LAST:event_ButtonCActionPerformed

    private void ButtonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSumActionPerformed
        this.Num1 = Float.parseFloat(this.Label_Ingreso.getText());
        this.Operator = "+";
        this.Label_Ingreso.setText("");
    }//GEN-LAST:event_ButtonSumActionPerformed

    private void ButtonResulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResulActionPerformed
        this.Num2 = Float.parseFloat(this.Label_Ingreso.getText());

        switch (this.Operator) {
            case "+":
                this.Label_Ingreso.setText(CalculoCero(this.Num1 + this.Num2));
                break;
            case "-":
                this.Label_Ingreso.setText(CalculoCero(this.Num1 - this.Num2));
                break;
            case "*":
                this.Label_Ingreso.setText(CalculoCero(this.Num1 * this.Num2));
                break;
            case "/":
                this.Label_Ingreso.setText(CalculoCero(this.Num1 / this.Num2));
                break;
        }
    }//GEN-LAST:event_ButtonResulActionPerformed

    private void ButtonResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResActionPerformed
        this.Num1 = Float.parseFloat(this.Label_Ingreso.getText());
        this.Operator = "-";
        this.Label_Ingreso.setText("");
    }//GEN-LAST:event_ButtonResActionPerformed

    private void ButtonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMulActionPerformed
        this.Num1 = Float.parseFloat(this.Label_Ingreso.getText());
        this.Operator = "*";
        this.Label_Ingreso.setText("");
    }//GEN-LAST:event_ButtonMulActionPerformed

    private void ButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivActionPerformed
        this.Num1 = Float.parseFloat(this.Label_Ingreso.getText());
        this.Operator = "/";
        this.Label_Ingreso.setText("");
    }//GEN-LAST:event_ButtonDivActionPerformed

    private void ButtonPuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPuntActionPerformed
        if (!(this.Label_Ingreso.getText().contains("."))) {
            this.Label_Ingreso.setText(this.Label_Ingreso.getText() + ".");
        }
    }//GEN-LAST:event_ButtonPuntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonCero;
    private javax.swing.JButton ButtonCinco;
    private javax.swing.JButton ButtonCuatro;
    private javax.swing.JButton ButtonDiv;
    private javax.swing.JButton ButtonDos;
    private javax.swing.JButton ButtonMul;
    private javax.swing.JButton ButtonNueve;
    private javax.swing.JButton ButtonOcho;
    private javax.swing.JButton ButtonPunt;
    private javax.swing.JButton ButtonRes;
    private javax.swing.JButton ButtonResul;
    private javax.swing.JButton ButtonSeis;
    private javax.swing.JButton ButtonSiete;
    private javax.swing.JButton ButtonSum;
    private javax.swing.JButton ButtonTres;
    private javax.swing.JButton ButtonUno;
    private javax.swing.JLabel Label_Ingreso;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
